name:  gcc build and test pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_gcc:
    runs-on: ["ubuntu-latest"]
 
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: make gcc
        run: |
          pwd
          echo "start building"
          cd src
          export CC=gcc
          make
          echo "done building"
          cd ..
          pwd

      - name: run test
        run: |
          pwd
          echo "start running test"
          cd test
          bash ./run_test.sh
          cd ..
          pwd

